language: python
dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION=1.11.*
  - DJANGO_VERSION=2.0.*
  - DJANGO_VERSION=2.1.*
  - DJANGO_VERSION=2.2.*

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0.*
    - python: "2.7"
      env: DJANGO_VERSION=2.1.*
    - python: "2.7"
      env: DJANGO_VERSION=2.2.*

jobs:
  include:
    - name: Check
      python: "3.6"
      install: pip install -U black mypy
      script: scripts/check

install:
  - pip install poetry
  - poetry install
  - pip install "django==$DJANGO_VERSION"

script:
  - scripts/test

before_deploy:
  - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
  - poetry build

deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
    # deploy only once
    python: "3.7"
    condition: "$DJANGO_VERSION = 2.2.*"
